# **Python 시작하기!**

## NumPy

이전 노트북에서 우리는 Python의 기본 사항과 AI 응용 프로그램에 Python이 인기 있는 이유를 배웠습니다. 또한 Python에서 사용할 수 있는 다양한 데이터 타입, 다양한 제어 옵션과 함께 제공되는 모듈 및 패키지에 대해서도 배웠습니다. 이제 과학 계산, 특히 배열과 관련된 계산을 수행하기 위해 Python에서 사용할 수 있는 가장 인기 있는 패키지 중 하나인 **NumPy**(Numerical'Num' Python'Py'의 줄임말)부터 시작하겠습니다. 시작합시다!

## Arrays

Python의 NumPy는 기본적으로 동일한 데이터 타입 값을 갖는 격자 배열입니다. NumPy 배열의 각 요소에는 음수가 아닌 인덱스를 가지고 있습니다. 배열을 다룰 때 각 차원에 따라 배열의 크기를 나타내는 shape라는 유용한 용어를 접하게 됩니다. 그렇다면 표준 Python List 대신 NumPy 배열을 사용하는 이유는 무엇입니까? NumPy 배열은 메모리 소비가 적고 런타임 동작도 개선되는데, 이것은 일반적으로 데이터 사이언스 분야의 계산에 있어 중요합니다. 우리가 많은 양의 데이터를 처리할 때 Python List와 NumPy 배열 처리의 차이는 상당히 많이 발생합니다. NumPy는 다차원 배열 및 행렬 데이터 구조를 포함하고 있으며 삼각법, 통계, 대수 루틴과 같은 배열에 대해 여러 수학적 연산을 수행할 수 있습니다.

In [3]:
import numpy as np #importing numpy package 
a = np.array([1,2,3]) #initializing an array with the elements given in the brackets
한글 = np.array(['가', '나', '다', '라'])
print (a)
print(한글)

[1 2 3]
['가' '나' '다' '라']


배열 'a'의 데이터 유형을 확인합시다.

In [8]:
# 여기에 데이터 유형을 확인하기 위한 코드를 작성하세요.
print(a.dtype)
print(한글.dtype)


int32
<U1


In [48]:
# 일차원 이상의 배열 만들기, 다차원 배열은 무조건 큰괄호[]가 2개 이상이 붙는다
b = np.array([[1, 2], [3, 4]]) 
print (b)
print('_'*20)
c1 = np.array([[1, 2, 3],[4 ,5, 6],[7, 8, 9]]) #2차원 응용
print(c1)
print('_'*20)
c2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 22, 23]],[[11, 12, 13], [14, 15, 16], [17, 18, 19], [24, 25, 26]]]) #3차원 만들기
print(c2)
print('_'*20)
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[1 2]
 [3 4]]
____________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [21 22 23]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]
  [24 25 26]]]
____________________
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:

linspace_arr = np.linspace(0 ,1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 지금까지 생성된 배열의 모양을 확인해 봅시다.
print("Shape of array 'a' is:",(a.shape))
print("Shape of array 'b' is:",(b.shape))
print("Shape of array '한글' is:",(한글.shape))
print("Shape of array 'c1' is:",(c1.shape))
print("Shape of array 'c2' is:",(c2.shape))

Shape of array 'a' is: (3, 2)
Shape of array 'b' is: (2, 2)
Shape of array '한글' is: (4,)
Shape of array 'c1' is: (3, 3)
Shape of array 'c2' is: (2, 4, 3)


In [33]:
# 인덱스를 사용하여 배열 요소에 접근해 봅시다.
#print(a[0], a[1], a[2]) 
#print(b[0][0]) # 첫 번째 행, 첫번째 열 요소를 print합니다.

print(c2[1][1][2])

16


In [34]:
# 배열의 특정 요소를 print 하는 또 다른 방법
print(b[0,1])
print(c2[0,1,1])

2
5


In [39]:
# arange 함수를 사용하여 배열 생성
c=np.arange(4)  # 첫 네 개의 요소를 0으로부터 print합니다.
print (c)
d=np.arange(1,7)# 시작점과 끝점 지정
print (d)

[0 1 2 3]
[1 2 3 4 5 6]


In [7]:
# 배열 이름을 'new'로 지정하여 (3, 4) 모양으로 다음 배열을 만듭니다.
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
new = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# 첫 슬라이싱은 2열로 구성된 하위 배열을 추출하는데 사용됩니다.
# 그리고 1:3 슬라이싱은 행1과 행 2를 추출하는데 사용됩니다.
# new_sub는 (2, 2) 모양을 갖는 배열입니다.

new_sub = new[:2, 1:3]
print(new_sub)

[[2 3]
 [6 7]]


**정수 배열 인덱싱** 

슬라이싱을 사용하여 numpy 배열을 인덱싱하면 결과 배열은 항상 원래 배열의 하위 배열이 됩니다. 반대로 정수 배열 인덱싱을 사용하면 다른 배열의 데이터를 사용하여 임의의 배열을 구성할 수 있습니다. 앞에서 배운 슬라이스 방법을 기억하시나요? 우리는 이전 노트북에서 이것을 경험하였습니다! Python의 인덱스는 항상 첫 번째 요소에 대해 0부터 시작한다는 것을 기억하십시오.

다음은 예입니다:

In [55]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print('_ '*50)
# a 배열에서 어떻게 [1 4 5]의 결과 값을 얻을 수 있을까요?
# '1'의 값은 a 배열의 첫 번째 괄호의 첫 번 째 'item'인 (0, 0) 위치에 있습니다.
# '4'의 값은 a 배열의 두 번째 괄호의 두 번 째 'item'인 (1, 1) 위치에 있습니다.
# '5'의 값을 얻는 방법을 생각해 보세요.

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


# 위의 내용은 다음과 같이 쓸 수도 있습니다.:
# a[0,0] '1'
# a[1,1] '4'
# a[2,0] '5'
# 이것은 정수 배열 인덱싱의 예입니다. 
# 앞선 인덱싱 예와 다음의 인덱싱 방식의 차이점을 자세히 살펴보십시오.
b=(a[[0, 1, 2], [0, 1, 0]])    # 이제 배열 인덱싱이 수행되는 방식과 이전 명령문과의 관계를 알 수 있습니까??  -  !!!이 부분 꼭 질문 다시 해야함!!!

print(b)       # Prints "[1 4 5]"
print(b.shape) # Shape는 3

[[1 2]
 [3 4]
 [5 6]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[1 4 5]
[1 4 5]
(3,)


In [40]:
# 위의 정수 배열 인덱싱은 다음과 같습니다.
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# 정수 배열 인덱싱을 사용할 때 소스 배열에서 동일한 요소를 재사용할 수 있습니다.
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# 이전 정수 배열 인덱싱 예제와 동일
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[2 2]
[2 2]


정수 인덱싱을 사용하여 배열의 특정 요소를 변경할 수도 있습니다.

In [41]:
# 인덱스 배열 생성
b = np.array([1, 0, 1])
print(b)

# b의 인덱스를 사용하여 a의 각 행에서 하나의 원소 선택
print(np.arange(3))  # 첫 번째 배열 인덱스
print(a[np.arange(3), b])

[1 0 1]
[0 1 2]
[2 3 6]


In [42]:
# b의 인덱스를 사용하여 a의 각 행에서 하나의 요소를 변경합니다.
a[np.arange(3), b] += 10

print(a)

[[ 1 12]
 [13  4]
 [ 5 16]]


## Datatypes in NumPy Arrays

In [43]:
roll_no = np.array([23, 46])   # numpy가 데이터 유형을 선택하도록 합니다.
print(roll_no.dtype)           # Prints "int64"

marks = np.array([65.5, 88.0]) # numpy가 데이터 유형을 선택하도록 합니다.
print(marks.dtype)             # Prints "float64"

int32
float64


In [44]:
x = np.array([1, 2], dtype=np.int64)   # 특정 데이터 타입으로 지정합니다.
print(x.dtype)                         # Prints "int64"

int64


**배열 수학**

기본적인 수학 연산은 배열에서 요소별로 적용할 수 있습니다. 이것은 (+,-,* 등)과 같은 연산자를 사용하거나 패키지 자체 내의 내장 함수를 사용하여 수행할 수 있습니다.

In [74]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 요소별 합계; 둘다 동일한 배열을 생성합니다.
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print("- "*20)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
- - - - - - - - - - - - - - - - - - - - 
[[ 6.  8.]
 [10. 12.]]


In [91]:
# 다음 요소를 사용하여 두 개의 배열 X 및 Y를 만들고 그 차이를 출력하는 코드를 작성하십시오.
X = [[13.0, 7.0],
    [4.0, 47.0]]
Y = [[16.0, 14.0],
    [1.0, 23.0]]

#print(X[0][0] - Y[0][0])

answer = []
for i in range(len(X)) :
    temp = []
    for j in range(len(X[0])) :
        temp.append(X[i][j] - Y[i][j])

    answer.append(temp)

print(answer)



[[-3.0, -7.0], [3.0, 24.0]]


In [58]:
X = np.array([[13.0,7.0],[4.0,47.0]], dtype=np.float64)
Y = np.array([[16.0,14.0],[1.0,23.0]], dtype=np.float64)
print (X-Y)
print(np.subtract(X, Y))

[[-3. -7.]
 [ 3. 24.]]
[[-3. -7.]
 [ 3. 24.]]


In [59]:
# 요소별 곱셈 수행
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


이것은 행렬 곱셈을 수행하는 것과 다릅니다. * 연산자는 요소별 곱셈에만 사용됩니다.

In [92]:
# 요소별 나눗셈 수행
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


NumPy 배열 정렬

In [97]:
a = np.array([1, 2, 3, 4, 5, 2, 1])
print(a)

[1 2 3 4 5 2 1]


In [100]:
np.sort(a) # 요소를 오름차순으로 정렬하는 함수
print (np.sort(a))
b = np.sort(a)
print(b)

[1 1 2 2 3 4 5]
[1 1 2 2 3 4 5]


In [102]:
np.flip(np.sort(a)) # 요소 순서를 반대로 배열하는 함수 방법 - sort에 대해 filp하는 것이다.
print (np.flip(np.sort(a)))

[5 4 3 2 2 1 1]


In [103]:
np.flip(np.sort(a))[:2]  # 슬라이싱 및 정렬
print (np.flip(np.sort(a))[:2])

[5 4]


## NumPy 배열 조작

reshape() 함수를 사용하면 요소를 변경하지 않고 배열의 모양을 변경할 수 있습니다. 이 함수의 구문은 아래에 설명되어 있습니다.

In [70]:
x=np.arange(12) # 12*1 배열 생성
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
y=x.reshape(6,2) # 12*1에서 6*2 배열로 모양 변경
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


List나 String을 연결하는 것처럼 배열도 연결할 수 있습니다. 다음 예에서는 3개의 1차원 배열을 하나의 배열로 연결합니다. 두 번째 배열의 요소는 첫 번째 배열에 추가됩니다. 그 후에 세 번째 배열의 요소가 추가됩니다.

In [72]:
x = np.array([3,12])
y = np.array([12,4,7])
z = np.array([2,6,8])
print(x)
print(y)
print(z)
c = np.concatenate((x,y,z)) # 연결을 수행하는 함수
print(c)

[ 3 12]
[12  4  7]
[2 6 8]
[ 3 12 12  4  7  2  6  8]


다차원 배열을 연결하는 경우 축에 따라 배열을 연결할 수 있습니다. concatenate()로 연결하려면 배열의 모양이 같아야 합니다. 다차원 배열의 경우 축에 따라 배열할 수 있습니다. 기본값은 axis = 0입니다.

In [107]:
x = np.array([[2,4],[7,9]])
print(x)
x=x.reshape(1,4)

print("X after reshape", x)
y = np.array([10,12,14,16])
print(y)
y=y.reshape(1,4)

print("Y after reshape", y)
c = np.concatenate((x,y),axis=1) # axis가 0은 행, 1은 열로 붙는다. 즉, 행 단위로, 또는 열 단위로 값이 아래나 우측 옆으로 붙게 된다.
print(c)

[[2 4]
 [7 9]]
X after reshape [[2 4 7 9]]
[10 12 14 16]
Y after reshape [[10 12 14 16]]
[[ 2  4  7  9 10 12 14 16]]


In [109]:
# 3차원 배열 연결하기

a = np.arange(24)
print(a)
b = a.reshape(2, 3, 4) # 우측 끝의 행렬을 기준으로 3차원, 4차원 등등이 생성된다.
print('reshaped : \n', b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**전문가 팁**: 유용한 기능 및 명령 목록을 항상 손쉽게 사용할 수 있도록 이 [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)를 활용할 수 있습니다.

# **Pandas**

Pandas는 NumPy를 기반으로 구축되었으며 Python에서 사용할 수 있는 가장 인기 있는 오픈 소스 패키지 중 하나입니다. 주요 유틸리티는 실제 데이터를 처리하기 위한 많은 기능을 제공합니다.

현재로서는 Pandas의 기능을 완전히 이해할 필요는 없습니다. 제공된 예제는 Pandas의 유용한 작동 중 일부를 보여주기 위한 것입니다. 이후 세션에서는 ML 워크플로에서 Pandas를 사용하는 방법에 대해 자세히 살펴보겠습니다.

그러나 코드들은 일반적으로 항상 비슷한 방식으로 사용되기 때문에 구문과 흐름 및 순서에 특별한 주의를 기울일 것을 제안합니다.

## Importing Pandas

In [110]:
# import 키워드 및 라이브러리 이름은 앞으로 공통으로 사용될 것입니다. 잘 기억해 두세요.
import pandas as pd

 **Data Frame**

Data frame은 2차원 데이터 구조입니다. 즉, 데이터는 행과 열을 갖는 표 형식으로 정렬됩니다.

DataFrame은 다양한 종류의 입력을 허용합니다. 더 자세한 내용을 알아보려면 온라인에서 검색하거나 [pandas'](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html) 문서를 참조하세요. 

<br>이 예제의 목적을 위해 DataFrame을 사용할 수 있는 유용한 방법을 보여주겠습니다. <br><br>우리는 날씨에 관심이 있고, 특히 [Open Government Data](https://data.gov.in/keywords/weather)에 관심이 있어서 (JaipurFinalCleanData.csv)라는 파일을 얻었다고 가정합시다. <br><br>쉼표로 구분된 값 또는 csv 파일은 이름에서 알 수 있듯이 쉼표로 구분된 데이터 집합이 포함되어 있으므로 이러한 파일은 Excel 또는 Google Sheet와 같은 스프레드시트 소프트웨어 사용자에게 친숙할 것입니다.
<br><br>이 예에서는 csv 파일을 Python에서 열고 DataFrame에 로드합니다.

<br><br> **Bonus Exercise:** Try loading in the file, and follow the rest of the exercise. Use your friend, the search engine and find a way to load your file into Colab!
파일을 로드하고 나머지 실행 코드를 따라해 보세요. 로컬 환경에서 Jupyter notebook을 이용하여 진행할 수도 있으며, 구글 [colab](https://colab.research.google.com/)와 같이 브라우저를 이용하여 진행할 수도 있습니다. 검색 엔진을 사용하여 파일을 Colab에 로드하는 방법을 찾아보세요.

In [3]:
# JaipurFinalCleanData.csv 파일은 이 노트북과 동일한 폴더에 있어야 합니다.

#First, create a variable we will call the DataFrame from
import pandas as pd
dataframe = pd.read_csv("JaipurFinalCleanData.csv")
print(dataframe.head())

         date  meantempm  maxtempm  mintempm  meantempm_1  meantempm_2  \
0  2016-05-04         34        41        27         35.0         36.0   
1  2016-05-05         31        38        24         34.0         35.0   
2  2016-05-06         28        34        21         31.0         34.0   
3  2016-05-07         30        38        23         28.0         31.0   
4  2016-05-08         34        41        26         30.0         28.0   

   meantempm_3  meandewptm_1  meandewptm_2  meandewptm_3  ...  mindewptm_3  \
0         34.0           6.0           4.0          -1.0  ...        -10.0   
1         36.0           7.0           6.0           4.0  ...         -2.0   
2         35.0          11.0           7.0           6.0  ...         -2.0   
3         34.0          13.0          11.0           7.0  ...          0.0   
4         31.0          10.0          13.0          11.0  ...          6.0   

   maxpressurem_1  maxpressurem_2  maxpressurem_3  minpressurem_1  \
0          1009.0

the .head() function by default shows the first 5 rows of a DataFrame, it also helps you to check if the csv file have loaded in correctly.

In [2]:
# 함수에 인수를 추가하여 더 많은 데이터를 표시할 수도 있습니다.
print(dataframe.head(10))

         date  meantempm  maxtempm  mintempm  meantempm_1  meantempm_2  \
0  2016-05-04         34        41        27         35.0         36.0   
1  2016-05-05         31        38        24         34.0         35.0   
2  2016-05-06         28        34        21         31.0         34.0   
3  2016-05-07         30        38        23         28.0         31.0   
4  2016-05-08         34        41        26         30.0         28.0   
5  2016-05-09         34        42        27         34.0         30.0   
6  2016-05-10         34        41        27         34.0         34.0   
7  2016-05-11         32        40        25         34.0         34.0   
8  2016-05-12         34        42        27         32.0         34.0   
9  2016-05-13         34        42        26         34.0         32.0   

   meantempm_3  meandewptm_1  meandewptm_2  meandewptm_3  ...  mindewptm_3  \
0         34.0           6.0           4.0          -1.0  ...        -10.0   
1         36.0           7.0 

In [3]:
# 또 다른 유용한 방법은 dataframe 내의 모든 데이터 타입을 확인할 수 있습니다. 
dataframe.dtypes

date                object
meantempm            int64
maxtempm             int64
mintempm             int64
meantempm_1        float64
meantempm_2        float64
meantempm_3        float64
meandewptm_1       float64
meandewptm_2       float64
meandewptm_3       float64
meanpressurem_1    float64
meanpressurem_2    float64
meanpressurem_3    float64
maxhumidity_1      float64
maxhumidity_2      float64
maxhumidity_3      float64
minhumidity_1      float64
minhumidity_2      float64
minhumidity_3      float64
maxtempm_1         float64
maxtempm_2         float64
maxtempm_3         float64
mintempm_1         float64
mintempm_2         float64
mintempm_3         float64
maxdewptm_1        float64
maxdewptm_2        float64
maxdewptm_3        float64
mindewptm_1        float64
mindewptm_2        float64
mindewptm_3        float64
maxpressurem_1     float64
maxpressurem_2     float64
maxpressurem_3     float64
minpressurem_1     float64
minpressurem_2     float64
minpressurem_3     float64
p

눈치채셨나요? DataFrame에서 print()를 사용하면 많은 값이 표시되지만 모든 값을 어떻게 이해해야 할까요? 바로 여기에서 데이터 시각화를 수행하고 그래프, 플롯 및 차트를 사용하여 우리가 보고 있는 것과 찾고 있는 것을 더 잘 이해할 수 있습니다. 다음 노트북에서는 유용하고 공통적인 라이브러리인 **matplotlib**에 대해 살펴보겠습니다.

In [4]:
s = pd.Series([1, 3, 7, 9,])
print(s)
print(type(s))

0    1
1    3
2    7
3    9
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
data = {'toy': ['gun', 'car', 'gun', 'car'], 'features': [25, 30, 35, 60]}

print('before DataFrame :', type(data))
df = pd.DataFrame(data)
print('after DataFrame :', type(df))

before DataFrame : <class 'dict'>
after DataFrame : <class 'pandas.core.frame.DataFrame'>


In [7]:
df

toy  features
0  gun        25
1  car        30
2  gun        35
3  car        60

In [9]:
print(df['toy'])
print("- "*100)
print(df[['toy', 'features']])

0    gun
1    car
2    gun
3    car
Name: toy, dtype: object
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
   toy  features
0  gun        25
1  car        30
2  gun        35
3  car        60


In [18]:
# 첫번째 행 출력
print(df.iloc[0])

print("- "*20)

print(df.loc[0])
print(type(df.iloc[0]))

print("- "*20)

print(df.iloc[[0]])
print(type(df.iloc[[0]]))

toy         gun
features     25
Name: 0, dtype: object
- - - - - - - - - - - - - - - - - - - - 
toy         gun
features     25
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
- - - - - - - - - - - - - - - - - - - - 
   toy  features
0  gun        25
<class 'pandas.core.frame.DataFrame'>


In [19]:
# features > 30 전체 행 출력
print(df[df['features'] > 30])

   toy  features
2  gun        35
3  car        60


In [20]:
# 데이터 프레임 추가하는 방법
df['color'] = ['grean', 'blue', 'yellow', 'white']
df

toy  features   color
0  gun        25   grean
1  car        30    blue
2  gun        35  yellow
3  car        60   white

In [21]:
print(df.isnull())   #이런 방식은 데이터가 적을 경우에는 가능하지만, 너무 많은 경우에는 하지 않는 방식이다.

     toy  features  color
0  False     False  False
1  False     False  False
2  False     False  False
3  False     False  False


In [22]:
df.iloc[1, 1] = None
print(df.isnull())
df

     toy  features  color
0  False     False  False
1  False      True  False
2  False     False  False
3  False     False  False


toy  features   color
0  gun      25.0   grean
1  car       NaN    blue
2  gun      35.0  yellow
3  car      60.0   white

In [23]:
#결측치 데이터 전체를 보는 방법이다. 근데 이렇게도 데이터가 많은 경우에는 찾아보기가 어렵다
print(df.isna())

     toy  features  color
0  False     False  False
1  False      True  False
2  False     False  False
3  False     False  False


In [24]:
#이 방법 또한 결측치 데이터를 보는 방법이다. 해당 열에 대해서만 결측치를 찾아본다.
print(df['features'].isna())

0    False
1     True
2    False
3    False
Name: features, dtype: bool


In [25]:
# 위 방법에 대해 유무를 찾는 any매소드이다. 있으면 true, 없으면 false이다.
print(df['features'].isna().any())

True


In [26]:
# 특정 열이 아니라 데이터 전체에 대해 결측치 데이터 유무를 보는 방법이다. any에 any를 넣는 것이다.
# 이 방법으로 우선 데이터 전체에 결측치 유무를 확인하고, 있다면 열 단위로 확인한 뒤, 데이터 전처리를 해야 한다.
print(df.isna().any().any())

True


In [29]:
#df.fillna(0, inplace=true) - 이 방법은 결측치에 대해 0으로 채우는 방법이다.
df.fillna(df['features'].mean(), inplace=True)
df

toy  features   color
0  gun      25.0   grean
1  car      40.0    blue
2  gun      35.0  yellow
3  car      60.0   white

In [31]:
print(df.describe())  # describe 메서드. 이 방법은 분포, 최대, 최소 등의 데이터를 보여준다. 숫자만 가능하다.

        features
count   4.000000
mean   40.000000
std    14.719601
min    25.000000
25%    32.500000
50%    37.500000
75%    45.000000
max    60.000000


In [32]:
df['key'] = [2, 3, 2, 4]
df

toy  features   color  key
0  gun      25.0   grean    2
1  car      40.0    blue    3
2  gun      35.0  yellow    2
3  car      60.0   white    4

In [58]:
# groupby는 그룹 단위(같은 값)으로 묶어서 분류를 할 수 있다
print(df.groupby('toy')['features'].sum())
print(df.groupby('toy')['features'].mean())

print("- "*20)

print(df.groupby('key')['features'].sum())
print(df.groupby('key')['features'].mean())

df2 = df.groupby('key')['features'].mean()
print(df2)


toy
car    100.0
gun     60.0
Name: features, dtype: float64
toy
car    50.0
gun    30.0
Name: features, dtype: float64
- - - - - - - - - - - - - - - - - - - - 
key
2    60.0
3    40.0
4    60.0
Name: features, dtype: float64
key
2    30.0
3    40.0
4    60.0
Name: features, dtype: float64
key
2    30.0
3    40.0
4    60.0
Name: features, dtype: float64


In [59]:
data3 = {'key': [2, 3], 'price': [200, 300]}
df3 = pd.DataFrame(data3)

df3

key  price
0    2    200
1    3    300

In [60]:
merged = pd.merge(df3 , df2 , on = 'key' , how = 'left')
merged

key  price  features
0    2    200      30.0
1    3    300      40.0

In [65]:
merged = pd.merge(df3 , df2 , on = 'key' , how = 'right')
merged

key  price  features
0    2  200.0      30.0
1    3  300.0      40.0
2    4    NaN      60.0

In [66]:
merged = pd.merge(df3 , df2 , on = 'key' , how = 'inner')
merged

key  price  features
0    2    200      30.0
1    3    300      40.0

In [67]:
merged = pd.merge(df3 , df2 , on = 'key' , how = 'outer')
merged

key  price  features
0    2  200.0      30.0
1    3  300.0      40.0
2    4    NaN      60.0

In [63]:
concat = pd.concat([df , df2] , axis = 1)
concat

toy  features   color  key  features
0  gun      25.0   grean  2.0       NaN
1  car      40.0    blue  3.0       NaN
2  gun      35.0  yellow  2.0      30.0
3  car      60.0   white  4.0      40.0
4  NaN       NaN     NaN  NaN      60.0

In [64]:
concat = pd.concat([df , df2] , axis = 0)
concat

toy  features   color  key     0
0  gun      25.0   grean  2.0   NaN
1  car      40.0    blue  3.0   NaN
2  gun      35.0  yellow  2.0   NaN
3  car      60.0   white  4.0   NaN
2  NaN       NaN     NaN  NaN  30.0
3  NaN       NaN     NaN  NaN  40.0
4  NaN       NaN     NaN  NaN  60.0